version: '2'
services:
  postgres:
    image: 'postgres:latest'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
